# Generated by Django 5.2.8 on 2025-12-04 02:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('department_id', models.AutoField(primary_key=True, serialize=False, verbose_name='부서 ID')),
                ('department_code', models.CharField(blank=True, max_length=10, null=True, verbose_name='부서코드')),
                ('department', models.CharField(blank=True, max_length=50, null=True, verbose_name='부서')),
            ],
            options={
                'verbose_name': '부서',
                'verbose_name_plural': '부서',
                'db_table': 'departments',
            },
        ),
        migrations.CreateModel(
            name='DoctorProfile',
            fields=[
                ('doctor_id', models.AutoField(primary_key=True, serialize=False, verbose_name='의사 ID')),
                ('name', models.CharField(max_length=50, verbose_name='이름')),
                ('sex', models.CharField(choices=[('male', '남성'), ('female', '여성')], max_length=6, verbose_name='성별')),
                ('phone', models.CharField(blank=True, max_length=11, null=True, verbose_name='연락처')),
                ('email', models.EmailField(blank=True, max_length=100, null=True, verbose_name='이메일')),
                ('password', models.CharField(blank=True, max_length=50, null=True, verbose_name='패스워드')),
                ('status', models.CharField(choices=[('on_duty', '근무중'), ('available', '대기중'), ('off_duty', '퇴근')], default='off_duty', max_length=9, verbose_name='근무상태')),
                ('position', models.CharField(blank=True, max_length=50, null=True, verbose_name='직책')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성일')),
                ('updated_at', models.DateTimeField(auto_now=True, null=True, verbose_name='수정일')),
                ('departments', models.ForeignKey(db_column='departments_id', on_delete=django.db.models.deletion.CASCADE, to='main.department', verbose_name='부서 ID')),
                ('user', models.ForeignKey(db_column='user_id', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='관리자 ID')),
            ],
            options={
                'verbose_name': '의사 프로필',
                'verbose_name_plural': '의사 프로필',
                'db_table': 'doctor_profiles',
            },
        ),
    ]
