# Generated by Django 5.2.8 on 2025-12-04 03:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctorprofile',
            name='email',
            field=models.EmailField(blank=True, max_length=100, null=True, unique=True, verbose_name='이메일'),
        ),
        migrations.AlterField(
            model_name='doctorprofile',
            name='phone',
            field=models.CharField(blank=True, max_length=11, null=True, unique=True, verbose_name='연락처'),
        ),
    ]
