# Generated by Django 5.2.8 on 2025-12-04 05:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_doctorprofile_email_alter_doctorprofile_phone'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DicomStudy',
            fields=[
                ('study_uid', models.CharField(max_length=100, primary_key=True, serialize=False, verbose_name='Study UID')),
                ('study_date', models.DateField(verbose_name='촬영 날짜')),
                ('study_desc', models.CharField(blank=True, max_length=255, null=True, verbose_name='검사 설명')),
                ('modality', models.CharField(default='CT', max_length=10, verbose_name='장비 종류')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성일')),
            ],
            options={
                'verbose_name': 'DICOM Study',
                'verbose_name_plural': 'DICOM Study',
                'db_table': 'dicom_studies',
            },
        ),
        migrations.CreateModel(
            name='Drug',
            fields=[
                ('drug_id', models.AutoField(primary_key=True, serialize=False, verbose_name='약물 ID')),
                ('name_kr', models.TextField(verbose_name='한글 약품명')),
                ('name_eng', models.TextField(verbose_name='영문 약품명')),
                ('drug_category', models.CharField(blank=True, max_length=100, null=True, verbose_name='약물 분류')),
                ('efficacy', models.TextField(blank=True, null=True, verbose_name='효능')),
                ('precautions', models.TextField(blank=True, null=True, verbose_name='주의사항')),
            ],
            options={
                'verbose_name': '약물',
                'verbose_name_plural': '약물',
                'db_table': 'drugs',
            },
        ),
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('patient_id', models.BigAutoField(primary_key=True, serialize=False, verbose_name='환자 ID')),
                ('name', models.CharField(max_length=100, verbose_name='이름')),
                ('birth_date', models.DateField(blank=True, null=True, verbose_name='생년월일')),
                ('sex', models.CharField(choices=[('male', '남성'), ('female', '여성')], max_length=6, verbose_name='성별')),
                ('resident_number', models.CharField(max_length=20, verbose_name='주민번호')),
                ('phone', models.CharField(max_length=11, verbose_name='연락처')),
                ('address', models.CharField(blank=True, max_length=255, null=True, verbose_name='주소')),
                ('diagnosis_date', models.DateField(blank=True, null=True, verbose_name='최초 암 진단일')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성일')),
            ],
            options={
                'verbose_name': '환자',
                'verbose_name_plural': '환자',
                'db_table': 'patients',
            },
        ),
        migrations.CreateModel(
            name='Announcement',
            fields=[
                ('announcement_id', models.BigAutoField(primary_key=True, serialize=False, verbose_name='공지 ID')),
                ('title', models.CharField(max_length=200, verbose_name='제목')),
                ('content', models.TextField(verbose_name='내용')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='작성일')),
                ('user', models.ForeignKey(db_column='user_id', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='작성자')),
            ],
            options={
                'verbose_name': '공지사항',
                'verbose_name_plural': '공지사항',
                'db_table': 'announcements',
            },
        ),
        migrations.CreateModel(
            name='DicomSeries',
            fields=[
                ('series_uid', models.CharField(max_length=100, primary_key=True, serialize=False, verbose_name='Series UID')),
                ('series_number', models.IntegerField(blank=True, null=True, verbose_name='시리즈 번호')),
                ('series_desc', models.CharField(blank=True, max_length=255, null=True, verbose_name='시리즈 설명')),
                ('phase_label', models.CharField(blank=True, choices=[('Arterial', 'Arterial'), ('Venous', 'Venous'), ('Delayed', 'Delayed'), ('Unknown', 'Unknown')], max_length=10, null=True, verbose_name='페이즈 라벨')),
                ('slice_count', models.IntegerField(blank=True, null=True, verbose_name='슬라이스 장수')),
                ('npy_path', models.CharField(blank=True, max_length=500, null=True, verbose_name='.npy 경로')),
                ('thumbnail_path', models.CharField(blank=True, max_length=500, null=True, verbose_name='썸네일 경로')),
                ('is_selected', models.BooleanField(default=False, verbose_name='학습 사용 여부')),
                ('study', models.ForeignKey(db_column='study_uid', on_delete=django.db.models.deletion.CASCADE, to='main.dicomstudy', verbose_name='Study UID')),
            ],
            options={
                'verbose_name': 'DICOM Series',
                'verbose_name_plural': 'DICOM Series',
                'db_table': 'dicom_series',
            },
        ),
        migrations.CreateModel(
            name='MedicalRecord',
            fields=[
                ('record_id', models.AutoField(primary_key=True, serialize=False, verbose_name='진료기록 ID')),
                ('visit_date', models.DateTimeField(auto_now_add=True, verbose_name='진료일시')),
                ('chief_complaint', models.CharField(blank=True, max_length=255, null=True, verbose_name='주증상')),
                ('subjective', models.TextField(blank=True, null=True, verbose_name='주관적 소견')),
                ('objective', models.TextField(blank=True, null=True, verbose_name='객관적 소견')),
                ('assessment', models.TextField(blank=True, null=True, verbose_name='진단 소견')),
                ('plan', models.TextField(blank=True, null=True, verbose_name='치료 계획')),
                ('doctor', models.ForeignKey(db_column='doctor_id', on_delete=django.db.models.deletion.CASCADE, to='main.doctorprofile', verbose_name='담당 의사')),
                ('patient', models.ForeignKey(db_column='patient_id', on_delete=django.db.models.deletion.CASCADE, to='main.patient', verbose_name='환자')),
            ],
            options={
                'verbose_name': '진료기록',
                'verbose_name_plural': '진료기록',
                'db_table': 'medical_records',
            },
        ),
        migrations.CreateModel(
            name='MedicalDiagnosis',
            fields=[
                ('diagnosis_id', models.AutoField(primary_key=True, serialize=False, verbose_name='진단 ID')),
                ('icd_code', models.CharField(blank=True, max_length=10, null=True, verbose_name='ICD-10 코드')),
                ('diagnosis_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='진단명')),
                ('record', models.ForeignKey(db_column='record_id', on_delete=django.db.models.deletion.CASCADE, to='main.medicalrecord', verbose_name='진료기록')),
            ],
            options={
                'verbose_name': '의학적 진단',
                'verbose_name_plural': '의학적 진단',
                'db_table': 'medical_diagnosis',
            },
        ),
        migrations.CreateModel(
            name='ClinicalRecord',
            fields=[
                ('clinical_id', models.AutoField(primary_key=True, serialize=False, verbose_name='임상검사 ID')),
                ('tumor_stage', models.CharField(blank=True, max_length=20, null=True, verbose_name='TNM 병기')),
                ('child_pugh', models.CharField(blank=True, max_length=5, null=True, verbose_name='Child-Pugh 등급')),
                ('afp', models.FloatField(blank=True, null=True, verbose_name='AFP 수치')),
                ('albumin', models.FloatField(blank=True, null=True, verbose_name='알부민')),
                ('bilirubin', models.FloatField(blank=True, null=True, verbose_name='빌리루빈')),
                ('platelet', models.FloatField(blank=True, null=True, verbose_name='혈소판')),
                ('creatinine', models.FloatField(blank=True, null=True, verbose_name='크레아티닌')),
                ('test_date', models.DateTimeField(auto_now_add=True, verbose_name='검사일')),
                ('record', models.ForeignKey(db_column='record_id', on_delete=django.db.models.deletion.CASCADE, to='main.medicalrecord', verbose_name='관련 진료기록')),
            ],
            options={
                'verbose_name': '임상기록',
                'verbose_name_plural': '임상기록',
                'db_table': 'clinical_records',
            },
        ),
        migrations.CreateModel(
            name='NurseProfile',
            fields=[
                ('nurse_id', models.AutoField(primary_key=True, serialize=False, verbose_name='간호사 ID')),
                ('name', models.CharField(max_length=50, verbose_name='이름')),
                ('sex', models.CharField(choices=[('male', '남성'), ('female', '여성')], max_length=6, verbose_name='성별')),
                ('phone', models.CharField(max_length=11, verbose_name='연락처')),
                ('email', models.EmailField(max_length=100, verbose_name='이메일')),
                ('position', models.CharField(blank=True, max_length=50, null=True, verbose_name='직급')),
                ('status', models.CharField(choices=[('on_duty', '근무중'), ('off_duty', '퇴근'), ('vacation', '휴가')], default='on_duty', max_length=10, verbose_name='근무상태')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성일')),
                ('department', models.ForeignKey(db_column='department_id', on_delete=django.db.models.deletion.CASCADE, to='main.department', verbose_name='부서 ID')),
                ('user', models.ForeignKey(db_column='user_id', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='계정 ID')),
            ],
            options={
                'verbose_name': '간호사 프로필',
                'verbose_name_plural': '간호사 프로필',
                'db_table': 'nurse_profiles',
            },
        ),
        migrations.CreateModel(
            name='NursingNote',
            fields=[
                ('note_id', models.AutoField(primary_key=True, serialize=False, verbose_name='간호기록 ID')),
                ('note_content', models.TextField(blank=True, null=True, verbose_name='간호 기록 내용')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='작성일')),
                ('nurse', models.ForeignKey(db_column='nurse_id', on_delete=django.db.models.deletion.CASCADE, to='main.nurseprofile', verbose_name='작성 간호사')),
                ('patient', models.ForeignKey(db_column='patient_id', on_delete=django.db.models.deletion.CASCADE, to='main.patient', verbose_name='환자')),
            ],
            options={
                'verbose_name': '간호기록',
                'verbose_name_plural': '간호기록',
                'db_table': 'nursing_notes',
            },
        ),
        migrations.CreateModel(
            name='MedicalVitals',
            fields=[
                ('vital_id', models.AutoField(primary_key=True, serialize=False, verbose_name='바이탈 ID')),
                ('height', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='신장')),
                ('weight', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='체중')),
                ('bp_systolic', models.IntegerField(blank=True, null=True, verbose_name='수축기 혈압')),
                ('bp_diastolic', models.IntegerField(blank=True, null=True, verbose_name='이완기 혈압')),
                ('heart_rate', models.IntegerField(blank=True, null=True, verbose_name='심박수')),
                ('temperature', models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True, verbose_name='체온')),
                ('measured_at', models.DateTimeField(auto_now_add=True, verbose_name='측정시각')),
                ('patient', models.ForeignKey(db_column='patient_id', on_delete=django.db.models.deletion.CASCADE, to='main.patient', verbose_name='환자')),
            ],
            options={
                'verbose_name': '바이탈',
                'verbose_name_plural': '바이탈',
                'db_table': 'medical_vitals',
            },
        ),
        migrations.AddField(
            model_name='dicomstudy',
            name='patient',
            field=models.ForeignKey(db_column='patient_id', on_delete=django.db.models.deletion.CASCADE, to='main.patient', verbose_name='환자'),
        ),
        migrations.CreateModel(
            name='AiPrediction',
            fields=[
                ('prediction_id', models.BigAutoField(primary_key=True, serialize=False, verbose_name='예측 ID')),
                ('risk_score', models.FloatField(blank=True, null=True, verbose_name='위험도 점수')),
                ('survival_prob_1yr', models.FloatField(blank=True, null=True, verbose_name='1년 생존확률')),
                ('survival_prob_3yr', models.FloatField(blank=True, null=True, verbose_name='3년 생존확률')),
                ('gradcam_path', models.CharField(blank=True, max_length=500, null=True, verbose_name='Grad-CAM 경로')),
                ('input_clinical_features', models.JSONField(blank=True, null=True, verbose_name='임상 특성 스냅샷')),
                ('input_gene_data', models.JSONField(blank=True, null=True, verbose_name='유전자 데이터 스냅샷')),
                ('analyzed_at', models.DateTimeField(auto_now_add=True, verbose_name='분석 시각')),
                ('series', models.ForeignKey(db_column='series_uid', on_delete=django.db.models.deletion.CASCADE, to='main.dicomseries', verbose_name='시리즈 UID')),
                ('patient', models.ForeignKey(db_column='patient_id', on_delete=django.db.models.deletion.CASCADE, to='main.patient', verbose_name='환자')),
            ],
            options={
                'verbose_name': 'AI 예측',
                'verbose_name_plural': 'AI 예측',
                'db_table': 'ai_predictions',
            },
        ),
        migrations.CreateModel(
            name='Prescription',
            fields=[
                ('prescription_id', models.AutoField(primary_key=True, serialize=False, verbose_name='처방전 ID')),
                ('drug_name', models.CharField(blank=True, max_length=100, null=True, verbose_name='약물명')),
                ('dosage', models.CharField(blank=True, max_length=50, null=True, verbose_name='용량')),
                ('frequency', models.CharField(blank=True, max_length=20, null=True, verbose_name='횟수')),
                ('duration', models.CharField(blank=True, max_length=20, null=True, verbose_name='기간')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='처방일')),
                ('record', models.ForeignKey(db_column='record_id', on_delete=django.db.models.deletion.CASCADE, to='main.medicalrecord', verbose_name='진료기록')),
            ],
            options={
                'verbose_name': '처방전',
                'verbose_name_plural': '처방전',
                'db_table': 'prescriptions',
            },
        ),
        migrations.CreateModel(
            name='TestOrder',
            fields=[
                ('order_id', models.AutoField(primary_key=True, serialize=False, verbose_name='오더 ID')),
                ('test_type', models.CharField(choices=[('CT', 'CT'), ('MRI', 'MRI'), ('US', 'US'), ('Blood', 'Blood'), ('Genomic', 'Genomic')], max_length=10, verbose_name='검사 종류')),
                ('body_part', models.CharField(blank=True, max_length=50, null=True, verbose_name='촬영 부위')),
                ('status', models.CharField(choices=[('Requested', 'Requested'), ('Scheduled', 'Scheduled'), ('Completed', 'Completed'), ('Canceled', 'Canceled')], default='Requested', max_length=10, verbose_name='진행 상태')),
                ('ordered_at', models.DateTimeField(auto_now_add=True, verbose_name='오더 시간')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='완료 시간')),
                ('record', models.ForeignKey(db_column='record_id', on_delete=django.db.models.deletion.CASCADE, to='main.medicalrecord', verbose_name='진료기록')),
            ],
            options={
                'verbose_name': '검사 오더',
                'verbose_name_plural': '검사 오더',
                'db_table': 'test_orders',
            },
        ),
        migrations.CreateModel(
            name='GenomicRecord',
            fields=[
                ('sample_id', models.AutoField(primary_key=True, serialize=False, verbose_name='샘플 ID')),
                ('sample_date', models.DateField(verbose_name='채취일')),
                ('gene_data', models.JSONField(verbose_name='유전자 발현량')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성일')),
                ('patient', models.ForeignKey(db_column='patient_id', on_delete=django.db.models.deletion.CASCADE, to='main.patient', verbose_name='환자')),
                ('order', models.ForeignKey(blank=True, db_column='order_id', null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.testorder', verbose_name='오더')),
            ],
            options={
                'verbose_name': '유전체 기록',
                'verbose_name_plural': '유전체 기록',
                'db_table': 'genomic_records',
            },
        ),
        migrations.AddField(
            model_name='dicomstudy',
            name='order',
            field=models.ForeignKey(blank=True, db_column='order_id', null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.testorder', verbose_name='오더'),
        ),
    ]
