# Generated by Django 5.2.8 on 2025-12-04 05:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_dicomstudy_drug_patient_announcement_dicomseries_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('appointment_id', models.AutoField(primary_key=True, serialize=False, verbose_name='예약 ID')),
                ('appointment_date', models.DateField(verbose_name='예약 날짜')),
                ('appointment_time', models.TimeField(verbose_name='예약 시간')),
                ('status', models.CharField(choices=[('scheduled', '예약됨'), ('completed', '완료'), ('cancelled', '취소')], default='scheduled', max_length=10, verbose_name='예약 상태')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='메모')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성일')),
                ('doctor', models.ForeignKey(db_column='doctor_id', on_delete=django.db.models.deletion.CASCADE, to='main.doctorprofile', verbose_name='담당 의사')),
                ('patient', models.ForeignKey(db_column='patient_id', on_delete=django.db.models.deletion.CASCADE, to='main.patient', verbose_name='환자')),
            ],
            options={
                'verbose_name': '예약',
                'verbose_name_plural': '예약',
                'db_table': 'appointments',
            },
        ),
    ]
