# Generated by Django 5.2.8 on 2025-12-05 06:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_appointment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='doctorprofile',
            name='password',
        ),
    ]
