# Generated by Django 5.2.7 on 2025-10-24 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Announcements",
            fields=[
                (
                    "announcements_id",
                    models.BigIntegerField(primary_key=True, serialize=False),
                ),
                ("title", models.CharField(max_length=200)),
                ("content", models.TextField()),
                ("created_at", models.DateTimeField()),
                ("updated_at", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "db_table": "announcements",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="AuthUsers",
            fields=[
                ("user_id", models.IntegerField(primary_key=True, serialize=False)),
                ("id", models.CharField(blank=True, max_length=150, null=True)),
                ("password", models.CharField(max_length=255)),
                ("last_login", models.DateTimeField(blank=True, null=True)),
                ("first_name", models.CharField(max_length=150)),
                ("last_name", models.CharField(max_length=150)),
                ("email", models.CharField(max_length=254)),
                ("is_staff", models.IntegerField()),
                ("is_active", models.IntegerField()),
                ("date_joined", models.DateTimeField()),
            ],
            options={
                "db_table": "auth_users",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="BloodResults",
            fields=[
                ("blood_id", models.IntegerField(primary_key=True, serialize=False)),
                (
                    "ast",
                    models.DecimalField(
                        blank=True,
                        db_column="AST",
                        decimal_places=2,
                        max_digits=10,
                        null=True,
                    ),
                ),
                (
                    "alt",
                    models.DecimalField(
                        blank=True,
                        db_column="ALT",
                        decimal_places=2,
                        max_digits=10,
                        null=True,
                    ),
                ),
                (
                    "alp",
                    models.DecimalField(
                        blank=True,
                        db_column="ALP",
                        decimal_places=2,
                        max_digits=10,
                        null=True,
                    ),
                ),
                (
                    "ggt",
                    models.DecimalField(
                        blank=True,
                        db_column="GGT",
                        decimal_places=2,
                        max_digits=10,
                        null=True,
                    ),
                ),
                (
                    "bilirubin",
                    models.DecimalField(
                        blank=True,
                        db_column="Bilirubin",
                        decimal_places=2,
                        max_digits=10,
                        null=True,
                    ),
                ),
                (
                    "albumin",
                    models.DecimalField(
                        blank=True,
                        db_column="Albumin",
                        decimal_places=2,
                        max_digits=10,
                        null=True,
                    ),
                ),
                (
                    "inr",
                    models.DecimalField(
                        blank=True,
                        db_column="INR",
                        decimal_places=3,
                        max_digits=10,
                        null=True,
                    ),
                ),
                (
                    "platelet",
                    models.DecimalField(
                        blank=True,
                        db_column="Platelet",
                        decimal_places=2,
                        max_digits=10,
                        null=True,
                    ),
                ),
                (
                    "afp",
                    models.DecimalField(
                        blank=True,
                        db_column="AFP",
                        decimal_places=2,
                        max_digits=10,
                        null=True,
                    ),
                ),
                ("taken_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "db_table": "blood_results",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="Departments",
            fields=[
                ("department_id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "department_code",
                    models.CharField(blank=True, max_length=10, null=True),
                ),
                ("department", models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                "db_table": "departments",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="DeseaseManage",
            fields=[
                (
                    "desease_manage_id",
                    models.BigIntegerField(primary_key=True, serialize=False),
                ),
                ("diagnosis_date", models.DateField(blank=True, null=True)),
                ("bclc_stage", models.CharField(blank=True, max_length=10, null=True)),
                ("tumor_size", models.FloatField(blank=True, null=True)),
                ("tumor_count", models.IntegerField(blank=True, null=True)),
                ("vascular_invasion", models.IntegerField()),
                ("child_pugh", models.CharField(blank=True, max_length=1, null=True)),
                ("afp_initial", models.FloatField(blank=True, null=True)),
                ("afp_current", models.FloatField(blank=True, null=True)),
                (
                    "treatment_type",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                ("treatment_start_date", models.DateField(blank=True, null=True)),
                (
                    "recurrence_risk",
                    models.CharField(blank=True, max_length=10, null=True),
                ),
            ],
            options={
                "db_table": "desease_manage",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="DoctorProfiles",
            fields=[
                (
                    "doctor_id",
                    models.CharField(max_length=50, primary_key=True, serialize=False),
                ),
                ("password", models.CharField(blank=True, max_length=128, null=True)),
                ("name", models.CharField(max_length=50)),
                ("sex", models.CharField(max_length=6)),
                ("phone", models.CharField(blank=True, max_length=11, null=True)),
                ("email", models.CharField(blank=True, max_length=100, null=True)),
                ("status", models.CharField(max_length=9)),
                ("profile_image", models.TextField(blank=True, null=True)),
                (
                    "license_number",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                ("position", models.CharField(blank=True, max_length=50, null=True)),
                ("last_login", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField()),
                ("updated_at", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "db_table": "doctor_profiles",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="DrugForm",
            fields=[
                ("form_id", models.AutoField(primary_key=True, serialize=False)),
                ("form", models.CharField(blank=True, max_length=30, null=True)),
            ],
            options={
                "db_table": "drug_form",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="DrugFrequency",
            fields=[
                ("frequency_id", models.AutoField(primary_key=True, serialize=False)),
                ("frequency", models.CharField(blank=True, max_length=10, null=True)),
            ],
            options={
                "db_table": "drug_frequency",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="DrugRoute",
            fields=[
                ("route_id", models.AutoField(primary_key=True, serialize=False)),
                ("route", models.CharField(blank=True, max_length=10, null=True)),
            ],
            options={
                "db_table": "drug_route",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="Drugs",
            fields=[
                ("drug_id", models.AutoField(primary_key=True, serialize=False)),
                ("name_kr", models.TextField()),
                ("name_eng", models.TextField()),
                ("drug_category", models.CharField(max_length=100)),
                ("dosage", models.TextField()),
                ("instructions", models.TextField(blank=True, null=True)),
                ("efficacy", models.TextField()),
                ("precautions", models.TextField()),
                ("common_side_effects", models.TextField()),
                ("serious_side_effects", models.TextField()),
                ("contraindications", models.TextField()),
                ("smiles", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField()),
                ("updated_at", models.DateTimeField()),
            ],
            options={
                "db_table": "drugs",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="MedicalDiagnosis",
            fields=[
                (
                    "diagnosis_id",
                    models.IntegerField(primary_key=True, serialize=False),
                ),
                ("icd_code", models.CharField(blank=True, max_length=10, null=True)),
                (
                    "diagnosis_name",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("is_primary", models.IntegerField(blank=True, null=True)),
            ],
            options={
                "db_table": "medical_diagnosis",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="MedicalRecords",
            fields=[
                ("record_id", models.IntegerField(primary_key=True, serialize=False)),
                ("visit_date", models.DateTimeField()),
                (
                    "chief_complatint",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("subjective_note", models.TextField(blank=True, null=True)),
                ("objective_note", models.TextField(blank=True, null=True)),
                ("assessment", models.TextField(blank=True, null=True)),
                ("plan", models.TextField(blank=True, null=True)),
            ],
            options={
                "db_table": "medical_records",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="MedicalSeries",
            fields=[
                ("series_id", models.IntegerField(primary_key=True, serialize=False)),
                ("slice_count", models.IntegerField(blank=True, null=True)),
                (
                    "thumbnail_path",
                    models.CharField(blank=True, max_length=500, null=True),
                ),
                (
                    "folder_path",
                    models.CharField(blank=True, max_length=500, null=True),
                ),
            ],
            options={
                "db_table": "medical_series",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="MedicalStudy",
            fields=[
                ("study_id", models.AutoField(primary_key=True, serialize=False)),
                ("modality", models.CharField(blank=True, max_length=3, null=True)),
                (
                    "instance_uid",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("body_part", models.CharField(blank=True, max_length=50, null=True)),
                ("study_date", models.DateTimeField(blank=True, null=True)),
                (
                    "description",
                    models.CharField(blank=True, max_length=200, null=True),
                ),
                ("indication", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "db_table": "medical_study",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="MedicalVitals",
            fields=[
                ("vital_id", models.IntegerField(primary_key=True, serialize=False)),
                (
                    "height",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=5, null=True
                    ),
                ),
                (
                    "weight",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=5, null=True
                    ),
                ),
                ("bp_systolic", models.IntegerField(blank=True, null=True)),
                ("bp_diastolic", models.IntegerField(blank=True, null=True)),
                ("heart_rate", models.IntegerField(blank=True, null=True)),
                ("resp_rate", models.IntegerField(blank=True, null=True)),
                (
                    "temperature",
                    models.DecimalField(
                        blank=True, decimal_places=1, max_digits=4, null=True
                    ),
                ),
                ("oxygen_saturation", models.IntegerField(blank=True, null=True)),
                ("measured_at", models.IntegerField(blank=True, null=True)),
            ],
            options={
                "db_table": "medical_vitals",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="NurseProfiles",
            fields=[
                ("nurse_id", models.IntegerField(primary_key=True, serialize=False)),
                ("name", models.CharField(blank=True, max_length=50, null=True)),
                ("sex", models.CharField(blank=True, max_length=6, null=True)),
                ("phone", models.CharField(blank=True, max_length=11, null=True)),
                ("email", models.CharField(blank=True, max_length=100, null=True)),
                ("status", models.CharField(blank=True, max_length=9, null=True)),
                ("profile_image", models.TextField(blank=True, null=True)),
                (
                    "license_number",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                ("shift_type", models.CharField(blank=True, max_length=7, null=True)),
                ("created_at", models.DateTimeField(blank=True, null=True)),
                ("updated_at", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "db_table": "nurse_profiles",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="NursingNotes",
            fields=[
                ("note_id", models.IntegerField(primary_key=True, serialize=False)),
                ("note_type", models.TextField(blank=True, null=True)),
                ("subjective_note", models.TextField(blank=True, null=True)),
                ("objective_note", models.TextField(blank=True, null=True)),
                ("assessment", models.TextField(blank=True, null=True)),
                ("plan", models.TextField(blank=True, null=True)),
                ("intervention", models.TextField(blank=True, null=True)),
                (
                    "abnormal_flag",
                    models.CharField(blank=True, max_length=8, null=True),
                ),
                ("next_action", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "db_table": "nursing_notes",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="Patients",
            fields=[
                (
                    "patient_id",
                    models.BigIntegerField(primary_key=True, serialize=False),
                ),
                ("name", models.CharField(max_length=100)),
                ("birth_date", models.DateField()),
                ("sex", models.CharField(max_length=6)),
                (
                    "resident_number",
                    models.CharField(blank=True, max_length=13, null=True),
                ),
                ("phone", models.CharField(max_length=11)),
                ("address", models.CharField(blank=True, max_length=255, null=True)),
                ("created_at", models.DateTimeField()),
                ("updated_at", models.DateTimeField()),
            ],
            options={
                "db_table": "patients",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="PrescriptionDrug",
            fields=[
                ("pd_id", models.IntegerField(primary_key=True, serialize=False)),
            ],
            options={
                "db_table": "prescription_drug",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="Prescriptions",
            fields=[
                (
                    "prescription_id",
                    models.IntegerField(primary_key=True, serialize=False),
                ),
                ("status", models.CharField(blank=True, max_length=8, null=True)),
                (
                    "medication_name",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("dosage", models.CharField(blank=True, max_length=50, null=True)),
                ("duration", models.CharField(blank=True, max_length=50, null=True)),
                ("quantity", models.IntegerField(blank=True, null=True)),
                ("due_date", models.DateTimeField()),
                ("comment", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(blank=True, null=True)),
                ("updated_at", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "db_table": "prescriptions",
                "managed": False,
            },
        ),
    ]
