# Generated by Django 5.2.7 on 2025-10-24 12:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("liverguard", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="announcements",
            options={
                "managed": False,
                "verbose_name": "공지사항",
                "verbose_name_plural": "공지사항",
            },
        ),
        migrations.AlterModelOptions(
            name="authusers",
            options={
                "managed": False,
                "verbose_name": "인증 사용자",
                "verbose_name_plural": "인증 사용자",
            },
        ),
        migrations.AlterModelOptions(
            name="bloodresults",
            options={
                "managed": False,
                "verbose_name": "혈액 검사",
                "verbose_name_plural": "혈액 검사",
            },
        ),
        migrations.AlterModelOptions(
            name="departments",
            options={
                "managed": False,
                "verbose_name": "부서",
                "verbose_name_plural": "부서",
            },
        ),
        migrations.AlterModelOptions(
            name="deseasemanage",
            options={
                "managed": False,
                "verbose_name": "질병 관리",
                "verbose_name_plural": "질병 관리",
            },
        ),
        migrations.AlterModelOptions(
            name="doctorprofiles",
            options={
                "managed": False,
                "verbose_name": "의사 프로필",
                "verbose_name_plural": "의사 프로필",
            },
        ),
        migrations.AlterModelOptions(
            name="drugform",
            options={
                "managed": False,
                "verbose_name": "약물 형태",
                "verbose_name_plural": "약물 형태",
            },
        ),
        migrations.AlterModelOptions(
            name="drugfrequency",
            options={
                "managed": False,
                "verbose_name": "투약 빈도",
                "verbose_name_plural": "투약 빈도",
            },
        ),
        migrations.AlterModelOptions(
            name="drugroute",
            options={
                "managed": False,
                "verbose_name": "투약 경로",
                "verbose_name_plural": "투약 경로",
            },
        ),
        migrations.AlterModelOptions(
            name="drugs",
            options={
                "managed": False,
                "verbose_name": "약물 정보",
                "verbose_name_plural": "약물 정보",
            },
        ),
        migrations.AlterModelOptions(
            name="medicaldiagnosis",
            options={
                "managed": False,
                "verbose_name": "진단",
                "verbose_name_plural": "진단",
            },
        ),
        migrations.AlterModelOptions(
            name="medicalrecords",
            options={
                "managed": False,
                "verbose_name": "진료 기록",
                "verbose_name_plural": "진료 기록",
            },
        ),
        migrations.AlterModelOptions(
            name="medicalseries",
            options={
                "managed": False,
                "verbose_name": "영상 시리즈",
                "verbose_name_plural": "영상 시리즈",
            },
        ),
        migrations.AlterModelOptions(
            name="medicalstudy",
            options={
                "managed": False,
                "verbose_name": "영상 검사",
                "verbose_name_plural": "영상 검사",
            },
        ),
        migrations.AlterModelOptions(
            name="medicalvitals",
            options={
                "managed": False,
                "verbose_name": "활력 징후",
                "verbose_name_plural": "활력 징후",
            },
        ),
        migrations.AlterModelOptions(
            name="nurseprofiles",
            options={
                "managed": False,
                "verbose_name": "간호사 프로필",
                "verbose_name_plural": "간호사 프로필",
            },
        ),
        migrations.AlterModelOptions(
            name="nursingnotes",
            options={
                "managed": False,
                "verbose_name": "간호 기록",
                "verbose_name_plural": "간호 기록",
            },
        ),
        migrations.AlterModelOptions(
            name="patients",
            options={
                "managed": False,
                "verbose_name": "환자",
                "verbose_name_plural": "환자",
            },
        ),
        migrations.AlterModelOptions(
            name="prescriptiondrug",
            options={
                "managed": False,
                "verbose_name": "처방 약물",
                "verbose_name_plural": "처방 약물",
            },
        ),
        migrations.AlterModelOptions(
            name="prescriptions",
            options={
                "managed": False,
                "verbose_name": "처방전",
                "verbose_name_plural": "처방전",
            },
        ),
    ]
