# Generated by Django 5.2.8 on 2025-11-13 05:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("HealthcareMap", "0002_alter_clinic_unique_together_and_more"),
        ("HealthcareMap", "0004_favoriteclinic_favoritehospital"),
    ]

    operations = []
