server {
  listen 9000;
  root /usr/share/nginx/html;
  index index.html;

  location / {
      try_files $uri /index.html;
  }

  location /api/ {
      proxy_pass http://django:8000;
  }

  location /orthanc/ {
    proxy_pass http://orthanc:8042/;

    proxy_set_header Host $host;
    proxy_set_header X-Real-IP $remote_addr;
    proxy_set_header Authorization $http_authorization;

    # ★ Orthanc UI가 /orthanc 하위 경로에서 정상 동작하도록 하는 핵심 설정
    proxy_set_header X-Forwarded-Prefix /orthanc;
    proxy_set_header X-Script-Name /orthanc;
    proxy_set_header X-Forwarded-Proto $scheme;

    # CORS
    add_header Access-Control-Allow-Origin *;
    add_header Access-Control-Allow-Methods "GET, POST, PUT, DELETE, PATCH, OPTIONS";
    add_header Access-Control-Allow-Headers "Authorization, Content-Type, Accept, Origin, X-Requested-With";

    if ($request_method = OPTIONS) {
        return 204;
    }
}
}