# Generated by Django 5.2.7 on 2025-11-12 05:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HealthcareMap', '0001_initial'),
        ('dashboard', '0006_remove_dbrpatients_resident_number_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='clinic',
            unique_together={('name', 'address')},
        ),
        migrations.AlterUniqueTogether(
            name='hospital',
            unique_together={('name', 'address')},
        ),
        migrations.AlterUniqueTogether(
            name='pharmacy',
            unique_together={('name', 'address')},
        ),
        migrations.CreateModel(
            name='FavoriteClinic',
            fields=[
                ('favorite_id', models.AutoField(primary_key=True, serialize=False, verbose_name='즐겨찾기 ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성일시')),
                ('clinic', models.ForeignKey(db_column='clinic_id', on_delete=django.db.models.deletion.CASCADE, related_name='favorited_by', to='HealthcareMap.clinic', verbose_name='의원 ID')),
                ('patient', models.ForeignKey(db_column='patient_id', on_delete=django.db.models.deletion.CASCADE, related_name='favorite_clinics', to='dashboard.dbrpatients', verbose_name='환자 ID')),
            ],
            options={
                'verbose_name': '의원 즐겨찾기',
                'verbose_name_plural': '의원 즐겨찾기',
                'db_table': 'favorite_clinic',
                'unique_together': {('patient', 'clinic')},
            },
        ),
        migrations.CreateModel(
            name='FavoriteHospital',
            fields=[
                ('favorite_id', models.AutoField(primary_key=True, serialize=False, verbose_name='즐겨찾기 ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성일시')),
                ('hospital', models.ForeignKey(db_column='hospital_id', on_delete=django.db.models.deletion.CASCADE, related_name='favorited_by', to='HealthcareMap.hospital', verbose_name='병원 ID')),
                ('patient', models.ForeignKey(db_column='patient_id', on_delete=django.db.models.deletion.CASCADE, related_name='favorite_hospitals', to='dashboard.dbrpatients', verbose_name='환자 ID')),
            ],
            options={
                'verbose_name': '병원 즐겨찾기',
                'verbose_name_plural': '병원 즐겨찾기',
                'db_table': 'favorite_hospital',
                'unique_together': {('patient', 'hospital')},
            },
        ),
    ]
