# Generated by Django 5.2.7 on 2025-11-03 01:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="dbrpatients",
            old_name="id",
            new_name="user_id",
        ),
    ]
