# Generated by Django 5.2.7 on 2025-11-03 03:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        # INSERT 트리거: 새 혈액검사 결과 입력 시 ALBI 자동 계산
        migrations.RunSQL(
            sql="""
            CREATE TRIGGER calculate_albi_on_insert
            BEFORE INSERT ON dbr_blood_results
            FOR EACH ROW
            BEGIN
                IF NEW.albumin IS NOT NULL AND NEW.bilirubin IS NOT NULL AND NEW.bilirubin > 0 THEN
                    SET NEW.albi = 0.66 * LOG10(17.1 * NEW.bilirubin) - 0.85 * NEW.albumin;
                END IF;
            END;
            """,
            reverse_sql="DROP TRIGGER IF EXISTS calculate_albi_on_insert;"
        ),

        # UPDATE 트리거: 혈액검사 결과 수정 시 ALBI 자동 재계산
        migrations.RunSQL(
            sql="""
            CREATE TRIGGER calculate_albi_on_update
            BEFORE UPDATE ON dbr_blood_results
            FOR EACH ROW
            BEGIN
                IF NEW.albumin IS NOT NULL AND NEW.bilirubin IS NOT NULL AND NEW.bilirubin > 0 THEN
                    SET NEW.albi = 0.66 * LOG10(17.1 * NEW.bilirubin) - 0.85 * NEW.albumin;
                END IF;
            END;
            """,
            reverse_sql="DROP TRIGGER IF EXISTS calculate_albi_on_update;"
        ),
    ]
