# Generated by Django 5.2.7 on 2025-11-12 05:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0005_remove_dbrpatients_resident_number_and_more'),
    ]

    operations = [
        # migrations.RemoveField(
        #     model_name='dbrpatients',
        #     name='resident_number',
        # ),
        # migrations.AlterField(
        #     model_name='dbrpatients',
        #     name='sex',
        #     field=models.CharField(choices=[('M', '남성'), ('F', '여성')], max_length=1, verbose_name='성별'),
        # ),
    ]
