# Generated by Django 5.2.8 on 2025-11-13 05:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0005_dbrbloodresults_albi_grade_dbrbloodresults_pt_and_more"),
        ("dashboard", "0006_remove_dbrpatients_resident_number_and_more"),
    ]

    operations = []
