# Generated by Django 5.2.7 on 2025-10-22 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("django_1pj", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="patient",
            name="ct_image",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to="ct_images/",
                verbose_name="간암 CT 이미지",
            ),
        ),
    ]
