# Generated by Django 5.2.7 on 2025-10-22 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("django_1pj", "0002_patient_ct_image"),
    ]

    operations = [
        migrations.CreateModel(
            name="Drug",
            fields=[
                (
                    "drug_code",
                    models.CharField(
                        max_length=50,
                        primary_key=True,
                        serialize=False,
                        verbose_name="약물 코드",
                    ),
                ),
                (
                    "drug_name_kr",
                    models.CharField(max_length=200, verbose_name="약물명(한글)"),
                ),
                (
                    "drug_name_en",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="약물명(영문)"
                    ),
                ),
                (
                    "drug_category",
                    models.CharField(
                        help_text="예: 항암제, 면역억제제 등",
                        max_length=100,
                        verbose_name="약물 분류",
                    ),
                ),
                ("dosage", models.TextField(blank=True, verbose_name="용법/용량")),
                ("efficacy", models.TextField(blank=True, verbose_name="효능/효과")),
                ("precautions", models.TextField(blank=True, verbose_name="주의사항")),
                (
                    "common_side_effects",
                    models.TextField(
                        blank=True,
                        help_text="줄바꿈으로 구분",
                        verbose_name="일반적인 부작용",
                    ),
                ),
                (
                    "serious_side_effects",
                    models.TextField(
                        blank=True,
                        help_text="줄바꿈으로 구분",
                        verbose_name="심각한 부작용",
                    ),
                ),
                (
                    "contraindications",
                    models.TextField(blank=True, verbose_name="금기사항"),
                ),
                (
                    "interactions",
                    models.TextField(blank=True, verbose_name="약물 상호작용"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "약물 정보",
                "verbose_name_plural": "약물 정보",
                "ordering": ["drug_name_kr"],
            },
        ),
        migrations.AddField(
            model_name="druginteraction",
            name="monitoring",
            field=models.TextField(
                blank=True,
                help_text="관찰해야 할 증상이나 검사 항목",
                verbose_name="모니터링 항목",
            ),
        ),
    ]
