# Generated by Django 5.2.7 on 2025-10-31 08:13

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="DbrBloodTestReferences",
            fields=[
                ("reference_id", models.AutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=50, verbose_name="검사 항목명")),
                (
                    "normal_range_min",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=6, null=True
                    ),
                ),
                (
                    "normal_range_max",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=6, null=True
                    ),
                ),
                (
                    "unit",
                    models.CharField(
                        blank=True, max_length=20, null=True, verbose_name="단위"
                    ),
                ),
                (
                    "description",
                    models.TextField(blank=True, null=True, verbose_name="설명"),
                ),
            ],
            options={
                "verbose_name": "혈액검사 기준",
                "verbose_name_plural": "혈액검사 기준 목록",
                "db_table": "dbr_blood_test_references",
                "managed": True,
            },
        ),
        migrations.CreateModel(
            name="DbrPatients",
            fields=[
                (
                    "patient_id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        verbose_name="환자 ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="이름")),
                ("birth_date", models.DateField(verbose_name="생년월일")),
                (
                    "sex",
                    models.CharField(
                        choices=[("male", "남성"), ("female", "여성")],
                        max_length=6,
                        verbose_name="성별",
                    ),
                ),
                (
                    "resident_number",
                    models.CharField(
                        blank=True,
                        max_length=13,
                        null=True,
                        verbose_name="주민등록번호",
                    ),
                ),
                (
                    "phone",
                    models.CharField(
                        blank=True, max_length=15, null=True, verbose_name="전화번호"
                    ),
                ),
                (
                    "address",
                    models.CharField(
                        blank=True, max_length=255, null=True, verbose_name="주소"
                    ),
                ),
                (
                    "height",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=5,
                        null=True,
                        verbose_name="신장(cm)",
                    ),
                ),
                (
                    "weight",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=5,
                        null=True,
                        verbose_name="체중(kg)",
                    ),
                ),
                (
                    "id",
                    models.CharField(
                        max_length=150, unique=True, verbose_name="로그인 ID"
                    ),
                ),
                ("password", models.CharField(max_length=128, verbose_name="비밀번호")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="생성일"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="수정일"),
                ),
            ],
            options={
                "verbose_name": "환자",
                "verbose_name_plural": "환자 목록",
                "db_table": "dbr_patients",
                "managed": True,
            },
        ),
        migrations.CreateModel(
            name="DbrBloodResults",
            fields=[
                (
                    "blood_result_id",
                    models.AutoField(primary_key=True, serialize=False),
                ),
                (
                    "ast",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=6, null=True
                    ),
                ),
                (
                    "alt",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=6, null=True
                    ),
                ),
                (
                    "alp",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=6, null=True
                    ),
                ),
                (
                    "ggt",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=6, null=True
                    ),
                ),
                (
                    "bilirubin",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=6, null=True
                    ),
                ),
                (
                    "albumin",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=6, null=True
                    ),
                ),
                (
                    "inr",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=6, null=True
                    ),
                ),
                (
                    "platelet",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=6, null=True
                    ),
                ),
                (
                    "afp",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=6, null=True
                    ),
                ),
                (
                    "albi",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=6, null=True
                    ),
                ),
                ("taken_at", models.DateField(verbose_name="검사일자")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="생성일"),
                ),
                (
                    "patient",
                    models.ForeignKey(
                        db_column="patient_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="blood_results",
                        to="dashboard.dbrpatients",
                        verbose_name="환자 ID",
                    ),
                ),
            ],
            options={
                "verbose_name": "혈액검사 결과",
                "verbose_name_plural": "혈액검사 결과 목록",
                "db_table": "dbr_blood_results",
                "managed": True,
            },
        ),
        migrations.CreateModel(
            name="DbrAppointments",
            fields=[
                ("appointment_id", models.AutoField(primary_key=True, serialize=False)),
                ("appointment_date", models.DateField(verbose_name="검사 일정")),
                (
                    "appointment_time",
                    models.TimeField(blank=True, null=True, verbose_name="검사 시간"),
                ),
                ("hospital", models.CharField(max_length=100, verbose_name="병원명")),
                (
                    "appointment_type",
                    models.CharField(
                        choices=[
                            ("blood_test", "혈액검사"),
                            ("ct", "CT 검사"),
                            ("mri", "MRI 검사"),
                            ("ultrasound", "초음파 검사"),
                            ("consultation", "진료 상담"),
                            ("other", "기타"),
                        ],
                        default="blood_test",
                        max_length=20,
                        verbose_name="검사 종류",
                    ),
                ),
                (
                    "details",
                    models.TextField(blank=True, null=True, verbose_name="자세한 내용"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("scheduled", "예정"),
                            ("completed", "완료"),
                            ("cancelled", "취소"),
                        ],
                        default="scheduled",
                        max_length=10,
                        verbose_name="상태",
                    ),
                ),
                (
                    "reminder_enabled",
                    models.BooleanField(default=True, verbose_name="알림 설정"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="생성일"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="수정일"),
                ),
                (
                    "patient",
                    models.ForeignKey(
                        db_column="patient_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="appointments",
                        to="dashboard.dbrpatients",
                        verbose_name="환자 ID",
                    ),
                ),
            ],
            options={
                "verbose_name": "검사 일정",
                "verbose_name_plural": "검사 일정 목록",
                "db_table": "dbr_appointments",
                "ordering": ["appointment_date", "appointment_time"],
                "managed": True,
            },
        ),
    ]
