# Generated by Django 5.2.7 on 2025-11-03 03:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0002_rename_id_dbrpatients_user_id"),
        ("dashboard", "0003_add_albi_trigger"),
    ]

    operations = []
