# Generated by Django 5.2.7 on 2025-11-12 03:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0004_merge_20251103_1245'),
    ]

    operations = [
        # migrations.RemoveField(
        #     model_name='dbrpatients',
        #     name='resident_number',
        # ),
        # migrations.AlterField(
        #     model_name='dbrpatients',
        #     name='sex',
        #     field=models.CharField(choices=[('M', '남성'), ('F', '여성')], max_length=1, verbose_name='성별'),
        # ),
        migrations.CreateModel(
            name='Medication',
            fields=[
                ('medication_id', models.AutoField(primary_key=True, serialize=False)),
                ('medication_name', models.CharField(max_length=200, verbose_name='약물명')),
                ('dosage', models.CharField(max_length=100, verbose_name='용량')),
                ('frequency', models.CharField(max_length=100, verbose_name='복용 빈도')),
                ('timing', models.CharField(max_length=100, verbose_name='복용 시간')),
                ('start_date', models.DateField(verbose_name='복용 시작일')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='복용 종료일')),
                ('is_active', models.BooleanField(default=True, verbose_name='활성 상태')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성일')),
                ('patient', models.ForeignKey(db_column='patient_id', on_delete=django.db.models.deletion.CASCADE, related_name='medications', to='dashboard.dbrpatients', verbose_name='환자 ID')),
            ],
            options={
                'verbose_name': '약물 정보',
                'verbose_name_plural': '약물 정보 목록',
                'db_table': 'dbr_medications',
                'ordering': ['-start_date'],
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='MedicationLog',
            fields=[
                ('log_id', models.AutoField(primary_key=True, serialize=False)),
                ('taken_date', models.DateField(verbose_name='복용 날짜')),
                ('taken_time', models.TimeField(verbose_name='복용 시간')),
                ('is_taken', models.BooleanField(default=True, verbose_name='복용 여부')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='메모')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성일')),
                ('medication', models.ForeignKey(db_column='medication_id', on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='dashboard.medication', verbose_name='약물 ID')),
            ],
            options={
                'verbose_name': '복용 기록',
                'verbose_name_plural': '복용 기록 목록',
                'db_table': 'dbr_medication_logs',
                'ordering': ['-taken_date', '-taken_time'],
                'managed': True,
            },
        ),
    ]
