# Generated by Django 5.2.7 on 2025-11-11 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0004_merge_20251103_1245"),
    ]

    operations = [
        migrations.AddField(
            model_name="dbrbloodresults",
            name="albi_grade",
            field=models.CharField(blank=True, max_length=7, null=True),
        ),
        migrations.AddField(
            model_name="dbrbloodresults",
            name="pt",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=6, null=True
            ),
        ),
        migrations.AddField(
            model_name="dbrbloodresults",
            name="r_gtp",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=6, null=True
            ),
        ),
        migrations.AddField(
            model_name="dbrbloodresults",
            name="risk_level",
            field=models.CharField(
                blank=True,
                choices=[
                    ("safe", "safe"),
                    ("warning", "warning"),
                    ("danger", "danger"),
                ],
                max_length=7,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="dbrbloodresults",
            name="total_protein",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=6, null=True
            ),
        ),
        migrations.AlterField(
            model_name="dbrbloodtestreferences",
            name="normal_range_max",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=7, null=True
            ),
        ),
        migrations.AlterField(
            model_name="dbrbloodtestreferences",
            name="normal_range_min",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=7, null=True
            ),
        ),
    ]
