# Generated by Django 5.2.8 on 2025-11-13 07:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0007_merge_20251113_1420"),
    ]

    operations = [
        migrations.RenameField(
            model_name="dbrappointments",
            old_name="patient",
            new_name="patient_id",
        ),
        migrations.RenameField(
            model_name="dbrbloodresults",
            old_name="patient",
            new_name="patient_id",
        ),
        migrations.RenameField(
            model_name="medication",
            old_name="patient",
            new_name="patient_id",
        ),
        migrations.RemoveField(
            model_name="dbrpatients",
            name="resident_number",
        ),
    ]
