# Generated by Django 5.2.7 on 2025-10-22 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("django_1pj", "0003_drug_druginteraction_monitoring"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="doctorprofile",
            name="user",
        ),
        migrations.AddField(
            model_name="doctorprofile",
            name="last_login",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="마지막 로그인"
            ),
        ),
        migrations.AddField(
            model_name="doctorprofile",
            name="password",
            field=models.CharField(
                default="pbkdf2_sha256$870000$temp$temppassword",
                max_length=128,
                verbose_name="비밀번호",
            ),
        ),
    ]
