# Generated by Django 5.2.7 on 2025-10-22 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "django_1pj",
            "0004_remove_doctorprofile_user_doctorprofile_last_login_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="doctorprofile",
            name="password",
            field=models.CharField(max_length=128, verbose_name="비밀번호"),
        ),
    ]
