# Generated by Django 5.2.7 on 2025-10-22 11:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Announcement",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200, verbose_name="제목")),
                ("content", models.TextField(verbose_name="내용")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="작성일"),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="활성화")),
            ],
            options={
                "verbose_name": "공지사항",
                "verbose_name_plural": "공지사항",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="DoctorProfile",
            fields=[
                (
                    "doctor_id",
                    models.CharField(
                        max_length=50,
                        primary_key=True,
                        serialize=False,
                        verbose_name="의사 ID",
                    ),
                ),
                ("doctor_name", models.CharField(max_length=100, verbose_name="이름")),
                (
                    "doctor_sex",
                    models.CharField(
                        choices=[("male", "남성"), ("female", "여성")],
                        max_length=10,
                        verbose_name="성별",
                    ),
                ),
                (
                    "doctor_phone",
                    models.CharField(
                        blank=True, max_length=20, null=True, verbose_name="전화번호"
                    ),
                ),
                (
                    "doctor_email",
                    models.EmailField(
                        blank=True, max_length=100, null=True, verbose_name="이메일"
                    ),
                ),
                (
                    "doctor_status",
                    models.CharField(
                        choices=[
                            ("진료중", "진료중"),
                            ("진료외", "진료외"),
                            ("휴무", "휴무"),
                        ],
                        default="진료외",
                        max_length=20,
                        verbose_name="상태",
                    ),
                ),
                (
                    "profile_image",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="doctor_profiles/",
                        verbose_name="프로필 이미지",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "의사 프로필",
                "verbose_name_plural": "의사 프로필",
            },
        ),
        migrations.CreateModel(
            name="Patient",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "patient_id",
                    models.CharField(
                        max_length=20, unique=True, verbose_name="환자번호"
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="이름")),
                ("birth_date", models.DateField(verbose_name="생년월일")),
                (
                    "gender",
                    models.CharField(
                        choices=[("M", "남성"), ("F", "여성")],
                        max_length=10,
                        verbose_name="성별",
                    ),
                ),
                (
                    "phone",
                    models.CharField(
                        blank=True, max_length=20, verbose_name="전화번호"
                    ),
                ),
                (
                    "diagnosis_date",
                    models.DateField(blank=True, null=True, verbose_name="진단일"),
                ),
                (
                    "bclc_stage",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("0", "Stage 0 (Very early)"),
                            ("A", "Stage A (Early)"),
                            ("B", "Stage B (Intermediate)"),
                            ("C", "Stage C (Advanced)"),
                            ("D", "Stage D (Terminal)"),
                        ],
                        max_length=10,
                        null=True,
                        verbose_name="BCLC 병기",
                    ),
                ),
                (
                    "tumor_size",
                    models.FloatField(
                        blank=True, null=True, verbose_name="종양크기(cm)"
                    ),
                ),
                (
                    "tumor_count",
                    models.IntegerField(blank=True, null=True, verbose_name="종양개수"),
                ),
                (
                    "vascular_invasion",
                    models.BooleanField(default=False, verbose_name="혈관침범"),
                ),
                (
                    "child_pugh",
                    models.CharField(
                        blank=True,
                        choices=[("A", "A"), ("B", "B"), ("C", "C")],
                        max_length=1,
                        null=True,
                        verbose_name="Child-Pugh 등급",
                    ),
                ),
                (
                    "afp_initial",
                    models.FloatField(
                        blank=True, null=True, verbose_name="초기 AFP(ng/mL)"
                    ),
                ),
                (
                    "afp_current",
                    models.FloatField(
                        blank=True, null=True, verbose_name="최근 AFP(ng/mL)"
                    ),
                ),
                (
                    "treatment_type",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("surgery", "수술적 절제"),
                            ("transplant", "간이식"),
                            ("tace", "TACE"),
                            ("sorafenib", "소라페닙"),
                            ("lenvatinib", "렌바티닙"),
                        ],
                        max_length=50,
                        null=True,
                        verbose_name="치료방식",
                    ),
                ),
                (
                    "treatment_start_date",
                    models.DateField(blank=True, null=True, verbose_name="치료시작일"),
                ),
                (
                    "survival_1year",
                    models.FloatField(
                        blank=True, null=True, verbose_name="1년 생존율(%)"
                    ),
                ),
                (
                    "survival_3year",
                    models.FloatField(
                        blank=True, null=True, verbose_name="3년 생존율(%)"
                    ),
                ),
                (
                    "survival_5year",
                    models.FloatField(
                        blank=True, null=True, verbose_name="5년 생존율(%)"
                    ),
                ),
                (
                    "recurrence_risk",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("low", "저위험"),
                            ("medium", "중위험"),
                            ("high", "고위험"),
                        ],
                        max_length=10,
                        null=True,
                        verbose_name="재발위험도",
                    ),
                ),
                (
                    "next_ct_date",
                    models.DateField(
                        blank=True, null=True, verbose_name="다음 CT 검사일"
                    ),
                ),
                (
                    "next_blood_test_date",
                    models.DateField(
                        blank=True, null=True, verbose_name="다음 혈액검사일"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "doctor",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="django_1pj.doctorprofile",
                        verbose_name="담당의",
                    ),
                ),
            ],
            options={
                "verbose_name": "환자",
                "verbose_name_plural": "환자",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="DrugInteraction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("drug_name", models.CharField(max_length=200, verbose_name="약물명")),
                (
                    "risk_level",
                    models.CharField(
                        choices=[
                            ("high", "고위험 (>50%)"),
                            ("medium", "중위험 (20-50%)"),
                            ("low", "저위험 (<20%)"),
                        ],
                        max_length=20,
                        verbose_name="위험도",
                    ),
                ),
                (
                    "side_effect",
                    models.CharField(max_length=200, verbose_name="부작용"),
                ),
                ("probability", models.IntegerField(verbose_name="발생 확률(%)")),
                (
                    "color_code",
                    models.CharField(
                        help_text="예: red, yellow, green",
                        max_length=20,
                        verbose_name="색상코드",
                    ),
                ),
                ("action_plan", models.TextField(blank=True, verbose_name="조치 계획")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "patient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="drug_interactions",
                        to="django_1pj.patient",
                        verbose_name="환자",
                    ),
                ),
            ],
            options={
                "verbose_name": "약물 상호작용",
                "verbose_name_plural": "약물 상호작용",
                "ordering": ["-probability"],
            },
        ),
    ]
